### ISSUE TITLE
Platforms removed too early

### ISSUE THREAD

**Issue by bojidar-bg** [fry-/fox_on_fire#1]
When playing on fc451040b3603f133e04931ff5013909e10c8e1a for long enough time, the "minifox" would fall off after some time, as platforms get removed before even reaching them.

And BTW, great job @fry- !

**Comment by fry-** [comment]
Thanks @bojidar-bg :smile: 
The (real) problem is that the minifox gets dragged in negative X-direction because of collision with the platforms. I tried to fix the problem whole day but I can't figure it out yet...

**Comment by fry-** [comment]
Temporarily fixed the unwanted x-direction movement of the player with 8ebc62874229d62cfdd34df3263e5a186ae1ebb6
